// Regenerate app icons from build/icon.svg:
//   build/icon.ico            (16/24/32/48/64/128/256, PNG-compressed entries)
//   electron/tray-icon-data.ts (base64 PNG constants for the tray, no runtime files)
// Run: node scripts/make-icons.mjs
import sharp from "sharp";
import fs from "fs";

const SVG = fs.readFileSync("build/icon.svg");
const SIZES = [16, 24, 32, 48, 64, 128, 256];

async function png(size) {
    // High density so the SVG rasterizes crisply before downscale.
    return sharp(SVG, {density: Math.ceil((72 * size) / 1024) * 4 + 72})
        .resize(size, size, {fit: "contain", background: {r: 0, g: 0, b: 0, alpha: 0}})
        .png()
        .toBuffer();
}

const pngs = await Promise.all(SIZES.map(png));

// BMP DIB entry (32-bit BGRA, bottom-up, + empty AND mask) — GDI+ cannot decode
// PNG-compressed entries below 256px, so every size except 256 must be a DIB.
async function dib(size) {
    const raw = await sharp(SVG, {density: Math.ceil((72 * size) / 1024) * 4 + 72})
        .resize(size, size, {fit: "contain", background: {r: 0, g: 0, b: 0, alpha: 0}})
        .raw().toBuffer(); // RGBA, top-down
    const header = Buffer.alloc(40);
    header.writeUInt32LE(40, 0);            // BITMAPINFOHEADER size
    header.writeInt32LE(size, 4);           // width
    header.writeInt32LE(size * 2, 8);       // height ×2 (XOR + AND masks)
    header.writeUInt16LE(1, 12);            // planes
    header.writeUInt16LE(32, 14);           // bpp
    const px = Buffer.alloc(size * size * 4); // BGRA bottom-up
    for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
            const s = ((size - 1 - y) * size + x) * 4, d = (y * size + x) * 4;
            px[d] = raw[s + 2]; px[d + 1] = raw[s + 1]; px[d + 2] = raw[s]; px[d + 3] = raw[s + 3];
        }
    }
    const andMask = Buffer.alloc((size / 8) * size); // all opaque (alpha channel rules)
    return Buffer.concat([header, px, andMask]);
}

const entryData = await Promise.all(SIZES.map((s, i) => (s === 256 ? pngs[i] : dib(s))));

// ---- ICO container ----
const header = Buffer.alloc(6);
header.writeUInt16LE(0, 0); // reserved
header.writeUInt16LE(1, 2); // type: icon
header.writeUInt16LE(SIZES.length, 4);

const entries = [];
let offset = 6 + 16 * SIZES.length;
for (let i = 0; i < SIZES.length; i++) {
    const e = Buffer.alloc(16);
    e[0] = SIZES[i] === 256 ? 0 : SIZES[i]; // width (0 = 256)
    e[1] = SIZES[i] === 256 ? 0 : SIZES[i]; // height
    e[2] = 0;                               // palette
    e[3] = 0;                               // reserved
    e.writeUInt16LE(1, 4);                  // planes
    e.writeUInt16LE(32, 6);                 // bpp
    e.writeUInt32LE(entryData[i].length, 8); // data size
    e.writeUInt32LE(offset, 12);            // data offset
    offset += entryData[i].length;
    entries.push(e);
}
fs.writeFileSync("build/icon.ico", Buffer.concat([header, ...entries, ...entryData]));
console.log(`build/icon.ico written (${SIZES.join("/")}px, ${offset} bytes)`);

// ---- Tray icon module (16 + 32 px embedded as base64) ----
const tray16 = pngs[SIZES.indexOf(16)].toString("base64");
const tray32 = pngs[SIZES.indexOf(32)].toString("base64");
fs.writeFileSync(
    "electron/tray-icon-data.ts",
    `// AUTO-GENERATED by scripts/make-icons.mjs from build/icon.svg - do not edit.\n` +
    `export const TRAY_ICON_16_B64 = "${tray16}";\n` +
    `export const TRAY_ICON_32_B64 = "${tray32}";\n`,
);
console.log("electron/tray-icon-data.ts written");

// Preview for eyeballing
fs.writeFileSync("build/icon-preview-256.png", pngs[SIZES.indexOf(256)]);
