// Regenerate app icons from build/icon.svg:
//   build/icon.ico            (16/24/32/48/64/128/256, PNG-compressed entries)
//   electron/tray-icon-data.ts (base64 PNG constants for the tray, no runtime files)
// Run: node scripts/make-icons.mjs
import sharp from "sharp";
import fs from "fs";

const SVG = fs.readFileSync("build/icon.svg");
const SIZES = [16, 24, 32, 48, 64, 128, 256];

async function png(size) {
    // High density so the SVG rasterizes crisply before downscale.
    return sharp(SVG, {density: Math.ceil((72 * size) / 1024) * 4 + 72})
        .resize(size, size, {fit: "contain", background: {r: 0, g: 0, b: 0, alpha: 0}})
        .png()
        .toBuffer();
}

const pngs = await Promise.all(SIZES.map(png));

// ---- ICO container (PNG entries are valid for all sizes on Win10+) ----
const header = Buffer.alloc(6);
header.writeUInt16LE(0, 0); // reserved
header.writeUInt16LE(1, 2); // type: icon
header.writeUInt16LE(SIZES.length, 4);

const entries = [];
let offset = 6 + 16 * SIZES.length;
for (let i = 0; i < SIZES.length; i++) {
    const e = Buffer.alloc(16);
    e[0] = SIZES[i] === 256 ? 0 : SIZES[i]; // width (0 = 256)
    e[1] = SIZES[i] === 256 ? 0 : SIZES[i]; // height
    e[2] = 0;                               // palette
    e[3] = 0;                               // reserved
    e.writeUInt16LE(1, 4);                  // planes
    e.writeUInt16LE(32, 6);                 // bpp
    e.writeUInt32LE(pngs[i].length, 8);     // data size
    e.writeUInt32LE(offset, 12);            // data offset
    offset += pngs[i].length;
    entries.push(e);
}
fs.writeFileSync("build/icon.ico", Buffer.concat([header, ...entries, ...pngs]));
console.log(`build/icon.ico written (${SIZES.join("/")}px, ${offset} bytes)`);

// ---- Tray icon module (16 + 32 px embedded as base64) ----
const tray16 = pngs[SIZES.indexOf(16)].toString("base64");
const tray32 = pngs[SIZES.indexOf(32)].toString("base64");
fs.writeFileSync(
    "electron/tray-icon-data.ts",
    `// AUTO-GENERATED by scripts/make-icons.mjs from build/icon.svg - do not edit.\n` +
    `export const TRAY_ICON_16_B64 = "${tray16}";\n` +
    `export const TRAY_ICON_32_B64 = "${tray32}";\n`,
);
console.log("electron/tray-icon-data.ts written");

// Preview for eyeballing
fs.writeFileSync("build/icon-preview-256.png", pngs[SIZES.indexOf(256)]);
